### ISSUE TITLE
New

### ISSUE THREAD

**Issue by anna08test** [Org1Watson/RepoW2#1]

**Comment by status-open-bounty** [comment]
Balance: 0.0010 ETH
Tokens: SNT: 0.00
Contract address: [0xb7a307d34f681f3d259b226fbc28a2ffb52dd3cc](https://ropsten.etherscan.io/address/0xb7a307d34f681f3d259b226fbc28a2ffb52dd3cc)
Network: Testnet (Ropsten)
Paid to: annadanchenko
