### ISSUE TITLE
Verify ETH and SNT

### ISSUE THREAD

**Issue by anna08test** [Org1Watson/RepoW2#12]

**Comment by status-open-bounty** [comment]
Balance: 0.0002 ETH
Tokens: SNT: 10.00
Contract address: [0xb0f6d5e2d4151034e8e9e727d7e89cbcd7fd4815](https://ropsten.etherscan.io/address/0xb0f6d5e2d4151034e8e9e727d7e89cbcd7fd4815)
Network: Testnet (Ropsten)
Paid to: annadanchenko
