### ISSUE TITLE
Verify only SNT

### ISSUE THREAD

**Issue by anna08test** [Org1Watson/RepoW2#13]

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 80.00
Contract address: [0xa12ed9b8076acbcda3a030cda3aa7aec9ddb760a](https://ropsten.etherscan.io/address/0xa12ed9b8076acbcda3a030cda3aa7aec9ddb760a)
Network: Testnet (Ropsten)
Status: pending maintainer confirmation
Winner: annadanchenko
