### ISSUE TITLE
Test SNT and ETH

### ISSUE THREAD

**Issue by anna08test** [Org1Watson/RepoW2#19]
snt first

**Comment by status-open-bounty** [comment]
Balance: 0.020000 ETH
Tokens: SNT: 11.00
Contract address: [0xd40a88a9d8696d847f9b727c11be6acfc5a96e52](https://ropsten.etherscan.io/address/0xd40a88a9d8696d847f9b727c11be6acfc5a96e52)
Network: Testnet (Ropsten)
Paid to: annadanchenko
