### ISSUE TITLE
Multicheck - Anton wins & sent eth to contract after claim is paid (so contract has 0.1 eth but it's not paid again :) )

### ISSUE THREAD

**Issue by anna08test** [Org1Watson/RepoW2#20]

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 24.00
Contract address: [0xc79a684b13284c89c8c4b0481aeb9a6bc32d830b](https://ropsten.etherscan.io/address/0xc79a684b13284c89c8c4b0481aeb9a6bc32d830b)
Network: Testnet (Ropsten)
Paid to: antdanchenko
