### ISSUE TITLE
Multicheck - Anna wins

### ISSUE THREAD

**Issue by anna08test** [Org1Watson/RepoW2#21]

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 13.00
Contract address: [0x3e18c27a53730b0c8e5d5e2c26873af695422466](https://ropsten.etherscan.io/address/0x3e18c27a53730b0c8e5d5e2c26873af695422466)
Network: Testnet (Ropsten)
Paid to: annadanchenko
