### ISSUE TITLE
no adddr

### ISSUE THREAD

**Issue by anna08test** [Org1Watson/RepoW2#29]

**Comment by status-open-bounty** [comment]
Balance: 0.100000 ETH
Contract address: [0x7c04fc3d09aac7b5a1ce1b745b4caa76d5272370](https://ropsten.etherscan.io/address/0x7c04fc3d09aac7b5a1ce1b745b4caa76d5272370)
Network: Testnet (Ropsten)
Status: Pending maintainer confirmation
Winner: annadanchenko
