### ISSUE TITLE
reproduce 151

### ISSUE THREAD

**Issue by anna08test** [Org1Watson/RepoW2#4]

**Comment by status-open-bounty** [comment]
Balance: 0.0002 ETH
Tokens: SNT: 0.00
Contract address: [0x7c120918ad2c7124ead5b65b8b3811f2dc6dfe8e](https://ropsten.etherscan.io/address/0x7c120918ad2c7124ead5b65b8b3811f2dc6dfe8e)
Network: Testnet (Ropsten)
Paid to: annadanchenko
