### ISSUE TITLE
SNT and ETH. wait 15 minutes -> submit PR, merge, confirm

### ISSUE THREAD

**Issue by anna08test** [Org1Watson/RepoW2#6]

**Comment by status-open-bounty** [comment]
Balance: 0.0002 ETH
Tokens: SNT: 0.00
Contract address: [0xe2cef89795849161545b26c1c1ba9bef4c8daf5e](https://ropsten.etherscan.io/address/0xe2cef89795849161545b26c1c1ba9bef4c8daf5e)
Network: Testnet (Ropsten)
Paid to: annadanchenko

**Comment by anna08test** [comment]
eth sent first
