### ISSUE TITLE
SNT ONLY. wait 15 minutes -> submit PR, merge, confirm

### ISSUE THREAD

**Issue by anna08test** [Org1Watson/RepoW2#7]

**Comment by status-open-bounty** [comment]
Balance: 0.0000 ETH
Tokens: SNT: 0.00
Contract address: [0x3cd45f8982c6fab0a0f2fabce01ea582f1f7526a](https://ropsten.etherscan.io/address/0x3cd45f8982c6fab0a0f2fabce01ea582f1f7526a)
Network: Testnet (Ropsten)
Paid to: annadanchenko
