### ISSUE TITLE
ETH ONLY. wait 15 minutes -> submit PR, merge, confirm

### ISSUE THREAD

**Issue by anna08test** [Org1Watson/RepoW2#8]

**Comment by status-open-bounty** [comment]
Balance: 0.0003 ETH
Contract address: [0x895390259c8990504b9b46cd938bfac7464e4653](https://ropsten.etherscan.io/address/0x895390259c8990504b9b46cd938bfac7464e4653)
Network: Testnet (Ropsten)
Paid to: annadanchenko
